/**
 * OpenSpec ID Generator
 *
 * Generates deterministic, path-based IDs for OpenSpec entities.
 * IDs are stable across syncs - the same input always produces the same output.
 *
 * ID Format:
 * - Specs: os-xxxx (e.g., os-a1b2)
 * - Changes: osc-xxxx (e.g., osc-c3d4)
 */

import { createHash } from "crypto";

/** Default prefix for OpenSpec spec IDs */
export const DEFAULT_SPEC_PREFIX = "os";

/** Default prefix for OpenSpec change IDs */
export const DEFAULT_CHANGE_PREFIX = "osc";

/** Default hash length (4 hex characters) */
const DEFAULT_HASH_LENGTH = 4;

/**
 * Generate a deterministic hash from an input string.
 * Uses SHA256 and takes the first N hex characters.
 *
 * @param input - The input string to hash
 * @param length - Number of hex characters to return (default: 4)
 * @returns Lowercase hex hash substring
 */
function generateHash(input: string, length: number = DEFAULT_HASH_LENGTH): string {
  const hash = createHash("sha256").update(input).digest("hex");
  return hash.substring(0, length).toLowerCase();
}

/**
 * Generate a deterministic spec ID from a capability name.
 *
 * The ID is generated by hashing "openspec-spec-{capability}" and
 * taking the first 4 hex characters.
 *
 * @param capability - The capability name (e.g., "cli-init")
 * @param prefix - ID prefix (default: "os")
 * @returns Deterministic spec ID (e.g., "os-a1b2")
 *
 * @example
 * generateSpecId("cli-init") // Returns same ID every time
 * generateSpecId("cli-init", "os") // Same as above, explicit prefix
 * generateSpecId("cli-init", "spec") // "spec-a1b2"
 */
export function generateSpecId(
  capability: string,
  prefix: string = DEFAULT_SPEC_PREFIX
): string {
  if (!capability || capability.trim() === "") {
    throw new Error("Capability name is required for spec ID generation");
  }

  const normalizedCapability = capability.trim().toLowerCase();
  const hashInput = `openspec-spec-${normalizedCapability}`;
  const hash = generateHash(hashInput);

  return `${prefix}-${hash}`;
}

/**
 * Generate a deterministic change ID from a change name.
 *
 * The ID is generated by hashing "openspec-change-{changeName}" and
 * taking the first 4 hex characters.
 *
 * @param changeName - The change name (e.g., "add-feature")
 * @param prefix - ID prefix (default: "osc")
 * @returns Deterministic change ID (e.g., "osc-c3d4")
 *
 * @example
 * generateChangeId("add-feature") // Returns same ID every time
 * generateChangeId("add-feature", "osc") // Same as above, explicit prefix
 * generateChangeId("add-feature", "ch") // "ch-c3d4"
 */
export function generateChangeId(
  changeName: string,
  prefix: string = DEFAULT_CHANGE_PREFIX
): string {
  if (!changeName || changeName.trim() === "") {
    throw new Error("Change name is required for change ID generation");
  }

  const normalizedChangeName = changeName.trim().toLowerCase();
  const hashInput = `openspec-change-${normalizedChangeName}`;
  const hash = generateHash(hashInput);

  return `${prefix}-${hash}`;
}

/**
 * Parsed result from an OpenSpec ID
 */
export interface ParsedOpenSpecId {
  /** Entity type: 'spec' or 'change' */
  type: "spec" | "change";
  /** The original name used to generate this ID (if recoverable) */
  name: string;
  /** The hash portion of the ID */
  hash: string;
  /** The prefix portion of the ID */
  prefix: string;
}

/**
 * Parse an OpenSpec ID to extract its components.
 *
 * Note: This only extracts structural information from the ID.
 * The original name cannot be recovered from the hash alone -
 * it must be provided or looked up separately.
 *
 * OpenSpec IDs require at least a 2-character prefix to distinguish
 * them from sudocode IDs (which use single-character prefixes like s- and i-).
 *
 * @param id - The OpenSpec ID to parse (e.g., "os-a1b2" or "osc-c3d4")
 * @returns Parsed ID components, or null if invalid format
 *
 * @example
 * parseOpenSpecId("os-a1b2")
 * // Returns: { type: "spec", name: "", hash: "a1b2", prefix: "os" }
 *
 * parseOpenSpecId("osc-c3d4")
 * // Returns: { type: "change", name: "", hash: "c3d4", prefix: "osc" }
 *
 * parseOpenSpecId("invalid")
 * // Returns: null
 *
 * parseOpenSpecId("s-abcd")
 * // Returns: null (sudocode format, not OpenSpec)
 */
export function parseOpenSpecId(id: string): ParsedOpenSpecId | null {
  if (!id || typeof id !== "string") {
    return null;
  }

  // Match pattern: prefix-hash where prefix is at least 2 characters
  // This distinguishes OpenSpec IDs (os-, osc-) from sudocode IDs (s-, i-)
  const match = id.match(/^([a-z]{2,})-([0-9a-f]{4,})$/i);

  if (!match) {
    return null;
  }

  const [, prefix, hash] = match;
  const normalizedPrefix = prefix.toLowerCase();

  // Determine type based on prefix
  // Default change prefix is "osc", default spec prefix is "os"
  // For custom prefixes, we use "osc" as the canonical change prefix
  const isChange = normalizedPrefix === DEFAULT_CHANGE_PREFIX;

  return {
    type: isChange ? "change" : "spec",
    name: "", // Cannot recover name from hash - must be looked up
    hash: hash.toLowerCase(),
    prefix: normalizedPrefix,
  };
}

/**
 * Verify that a given ID matches the expected ID for a name.
 *
 * Useful for validating that an ID was generated correctly.
 *
 * @param id - The ID to verify
 * @param name - The name that should produce this ID
 * @param type - Entity type ('spec' or 'change')
 * @returns True if the ID matches what would be generated from the name
 *
 * @example
 * verifyOpenSpecId("os-a1b2", "cli-init", "spec") // true or false
 */
export function verifyOpenSpecId(
  id: string,
  name: string,
  type: "spec" | "change"
): boolean {
  const parsed = parseOpenSpecId(id);
  if (!parsed) {
    return false;
  }

  const expectedId =
    type === "spec"
      ? generateSpecId(name, parsed.prefix)
      : generateChangeId(name, parsed.prefix);

  return id.toLowerCase() === expectedId.toLowerCase();
}

/**
 * Check if a string is a valid OpenSpec ID format.
 *
 * @param id - The string to check
 * @returns True if the string matches OpenSpec ID format
 *
 * @example
 * isOpenSpecId("os-a1b2")  // true
 * isOpenSpecId("osc-c3d4") // true
 * isOpenSpecId("invalid")  // false
 * isOpenSpecId("s-abcd")   // false (sudocode format, not OpenSpec)
 */
export function isOpenSpecId(id: string): boolean {
  return parseOpenSpecId(id) !== null;
}
